export const CLIENTNOTES = 'CLIENTNOTES';
export const CLIENTNOTES_SUCCESS = 'CLIENTNOTES_SUCCESS';
export const CLIENTNOTES_ERROR = 'CLIENTNOTES_ERROR';

export const CLIENTNOTES_GET = 'CLIENTNOTES_GET';
export const CLIENTNOTES_GET_SUCCESS = 'CLIENTNOTES_GET_SUCCESS';
export const CLIENTNOTES_GET_ERROR = 'CLIENTNOTES_GET_ERROR';

export const CLIENTNOTES_CREATE = 'CLIENTNOTES_CREATE';
export const CLIENTNOTES_CREATE_SUCCESS = 'CLIENTNOTES_CREATE_SUCCESS';
export const CLIENTNOTES_CREATE_ERROR = 'CLIENTNOTES_CREATE_ERROR';

export const CLIENTNOTES_UPDATE = 'CLIENTNOTES_UPDATE';
export const CLIENTNOTES_UPDATE_SUCCESS = 'CLIENTNOTES_UPDATE_SUCCESS';
export const CLIENTNOTES_UPDATE_ERROR = 'CLIENTNOTES_UPDATE_ERROR';